name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master
      - releases/*
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test

  test:
    runs-on: self-hosted

    steps:
      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v2

      # Basic checkout
      - name: Checkout basic
        uses: ./
        with:
          ref: test-data/v2/basic
          path: basic/
      - name: Verify basic
        shell: bash
        run: |
          ls -ltr ./
          ls -ltr ./basic/checkout/
          __test__/verify-basic.sh

      # Clean
      - name: Modify work tree
        shell: bash
        run: __test__/modify-work-tree.sh
      - name: Checkout clean
        uses: ./
        with:
          ref: test-data/v2/basic
          path: basic/
      - name: Verify clean
        shell: bash
        run: __test__/verify-clean.sh

      # Side by side
      - name: Checkout side by side 1
        uses: ./
        with:
          ref: test-data/v2/side-by-side-1
          path: side-by-side-1/
      - name: Checkout side by side 2
        uses: ./
        with:
          ref: test-data/v2/side-by-side-2
          path: side-by-side-2/
      - name: Verify side by side
        shell: bash
        run: __test__/verify-side-by-side.sh
